# Generated by Django 4.2.5 on 2023-09-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=264)),
                ("lastName", models.CharField(max_length=264)),
                ("email", models.CharField(max_length=264)),
            ],
        ),
    ]
