# Generated by Django 4.2.5 on 2023-09-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first_app", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("text", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="firstName",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="lastName",
            new_name="lastname",
        ),
    ]
